K8SPG-89 Add TLS secrets fields
percona/percona-postgresql-operator pull request #123
Opened 2021-09-06 16:24 UTC by nonemax

2021-09-06 19:59 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/bc5fabc4c76926cc239ac87cca346793d3571a6d
image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-deployer`

2021-09-07 15:55 UTC, cap1984 commented
@nonemax please add tls check test

2021-09-08 11:52 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/bc5fabc4c76926cc239ac87cca346793d3571a6d
image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-bc5fabc4-pgo-deployer`

2021-09-08 12:09 UTC, hors requested changes

2021-09-08 12:09 UTC, hors commented on e2e-tests/tls-check/run
> +	"postgres:postgres_pass@${cluster}.${namespace}"
I think we need to connect to postgres  via pgBouncer  and using certificate. And also we need to check not only creation of cluster with ssl but also its update  (enable/disable ssl on existing one ).

2021-09-08 14:27 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | failed |
| operator-self-healing | passed |
| clone-cluster | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/76aba1647c2b4eb52d7456179087a4e1ea3ad081
image: `perconalab/percona-postgresql-operator:PR-123-76aba164-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-76aba164-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-76aba164-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-76aba164-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-76aba164-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-76aba164-pgo-deployer`

2021-09-09 06:39 UTC, cap1984 commented on e2e-tests/tls-check/run
> +	"postgres:postgres_pass@${cluster}.${namespace}"
I believe we need to test all four mods from https://www.postgresql.org/docs/8.4/libpq-connect.html#LIBPQ-CONNECT-SSLMODE

2021-09-13 13:25 UTC, cap1984 commented on e2e-tests/tls-check/conf/client.yml
> +              mountPath: "/etc/tls"
tmp/tls please

2021-09-13 16:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/6e409734c32869ca3df2cf426635a3cfc5423085
image: `perconalab/percona-postgresql-operator:PR-123-6e409734-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-6e409734-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-6e409734-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-6e409734-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-6e409734-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-6e409734-pgo-deployer`

2021-09-14 12:09 UTC, egegunes requested changes

2021-09-14 12:09 UTC, egegunes commented on percona/controllers/pgcluster/pgcluster.go
> +		if err != nil && strings.Contains(err.Error(), "not found") {
Is it possible to check it with `kubeapi.IsNotFound`?

2021-09-14 12:09 UTC, egegunes commented on percona/controllers/pgcluster/pgcluster.go
> +func UpdatePgBouncer(clientset *kubeapi.Client, newPerocnaPGCluster, oldPerocnaPGCluster *crv1.PerconaPGCluster) error {
typo `Perocna` on multiple locations in the function

2021-09-14 12:09 UTC, egegunes commented on percona/controllers/pgc/pgc.go
> +			log.Errorf("update perconapgcluster: update pgreplica: %s", err)
should we continue after logging the error?

2021-09-14 14:49 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| clone-cluster | passed |
| tls-check | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/d2042da50e456f6c2060b42a799ce1f39c5bee5b
image: `perconalab/percona-postgresql-operator:PR-123-d2042da5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-d2042da5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-d2042da5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-d2042da5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-d2042da5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-d2042da5-pgo-deployer`

2021-09-14 16:26 UTC, egegunes approved these changes

2021-09-14 18:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/f4344f910a0bad5d35e7aab7a13b9eef2e8b3d6f
image: `perconalab/percona-postgresql-operator:PR-123-f4344f91-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-f4344f91-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-f4344f91-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-f4344f91-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-f4344f91-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-f4344f91-pgo-deployer`

2021-09-14 19:43 UTC, cap1984 approved these changes

2021-09-15 09:20 UTC, hors approved these changes

2021-09-15 09:49 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/c2322ddf811a1a9aff2abfd8e9b368ca2510aa1d
image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-deployer`

2021-09-15 12:33 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | failed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | failed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| clone-cluster | passed |
| tls-check | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/c2322ddf811a1a9aff2abfd8e9b368ca2510aa1d
image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-c2322ddf-pgo-deployer`

2021-09-15 22:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| data-migration-gcs | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/123/commits/a8dc9a2478344a1452ecd4a06fe93cb1650cd467
image: `perconalab/percona-postgresql-operator:PR-123-a8dc9a24-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-123-a8dc9a24-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-123-a8dc9a24-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-123-a8dc9a24-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-123-a8dc9a24-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-123-a8dc9a24-pgo-deployer`

2021-09-16 09:26 UTC, merged