K8SPG-94 document openshift
percona/percona-postgresql-operator pull request #133
Opened 2021-09-27 12:21 UTC by fiowro

2021-09-27 12:50 UTC, cap1984 approved these changes

2021-10-01 08:26 UTC, spron-in requested changes

2021-10-01 08:26 UTC, spron-in commented on source/openshift.rst
> +`Red Hat Certified Operator <https://connect.redhat.com/en/partner-with-us/red-hat-openshift-certification>`_.
come on! we are not certified @cap1984

2021-10-01 16:54 UTC, spron-in approved these changes

2021-10-01 16:58 UTC, merged