K8SPG-63 scheduled bacups doc
percona/percona-postgresql-operator pull request #134
Opened 2021-09-28 08:15 UTC by fiowro

2021-09-29 14:47 UTC, cap1984 approved these changes

2021-10-01 08:24 UTC, spron-in requested changes

2021-10-01 08:24 UTC, spron-in commented on source/backups.rst
> +Making scheduled backups
```suggestion
Scheduling backups
```

2021-10-01 08:24 UTC, spron-in commented on source/backups.rst
> +        storage: local
```suggestion
        storage: s3
```
does not look like s3 :)

2021-10-01 08:24 UTC, spron-in commented on source/backups.rst
> +        keep: 3
I don't see any explanation about `keep` flag.

2021-10-01 16:54 UTC, spron-in approved these changes

2021-10-01 17:02 UTC, merged