K8SPG-135 document imagePullPolicy option
percona/percona-postgresql-operator pull request #169
Opened 2021-11-29 21:34 UTC by fiowro

2021-12-01 10:10 UTC, spron-in approved these changes

2021-12-02 12:58 UTC, hors commented on source/glossary.rst
> +   imagePullPolicy
@spron-in  I have re-check and we do not support it for now at all. I am going to create task about it,

2022-01-03 12:29 UTC, hors requested changes

2022-01-03 12:29 UTC, hors commented on source/glossary.rst
> +      :ref:`pgReplicas.REPLICA_NAME.imagePullPolicy<pgreplicas-imagepullpolicy>`
We will not have separate option for `pgReplicas`. The `imagePullPolicy` from `pgPrimary` will be used for `pgReplicas`.

2022-02-22 12:55 UTC, hors commented on source/glossary.rst
> +      :ref:`pgReplicas.REPLICA_NAME.imagePullPolicy<pgreplicas-imagepullpolicy>`
@fiowro it was fixed and now we can merge it. So, please fix conflicts.

2022-03-01 09:19 UTC, spron-in approved these changes

2022-03-08 08:44 UTC, spron-in reviewed
Change the wording to "This option is used to set the policy for ..."

2022-03-08 12:54 UTC, hors approved these changes

2022-03-09 09:22 UTC, merged