K8SPG-101 document horizontal scaling
percona/percona-postgresql-operator pull request #170
Opened 2021-11-29 21:35 UTC by fiowro

2021-12-01 10:10 UTC, spron-in requested changes

2021-12-01 10:10 UTC, spron-in commented on source/scaling.rst
> +replica instances.
I would emphasize here, that we change only the number of Replicas. So the size of the cluster here should be 5 Replicas + 1 Primary.

2021-12-01 10:10 UTC, spron-in commented on source/scaling.rst
> +Scale Percona Distribution for PostgreSQL on Kubernetes and OpenShift
not now, but for later on we need to have Horizontal Pod Autoscaler (HPA) example here + also add more information about vertical scaling and if it is possible to integrate with Vertical Pod Autoscaler (VPA).

2021-12-03 13:40 UTC, spron-in approved these changes

2021-12-03 14:00 UTC, nonemax approved these changes

2021-12-03 14:04 UTC, merged