K8SPG-129 document custom configuration
percona/percona-postgresql-operator pull request #171
Opened 2021-11-30 08:32 UTC by fiowro

2021-12-01 10:07 UTC, spron-in requested changes

2021-12-01 10:07 UTC, spron-in commented on source/options.rst
> +         customconfig: |
in other operators we have `configuration` not `customconfig`. Is it something we inherited @hors  ?

2021-12-01 10:07 UTC, spron-in commented on source/options.rst
> +data inside a containerized application.
```suggestion
You can use a ConfigMap and the cluster restart to reset configuration
options. A ConfigMap allows Kubernetes to pass or update configuration
data inside a containerized application.
```

2021-12-01 10:07 UTC, spron-in commented on source/options.rst
> +Do not forget to restart the cluster to ensure it has updated the configuration
I don't understand this section. 

1. should I restart if I create configmap or if I apply config with cr.yaml? Both?
2. How do I restart? 
3. Aren't we restarting automatically?

2021-12-01 10:07 UTC, spron-in commented on source/options.rst
> +(see details on how to connect in the `Install Percona Distribution for PostgreSQL on Kubernetes <kubernetes.html>`_ page).
I don't think this is relevant and you wanted to have a link to how to restart here?

2021-12-01 10:07 UTC, spron-in commented on source/options.rst
> +* use a ConfigMap.
If I use this, will my PostgreSQL configuration be rewritten or appended to existing ones? We need to mention this.

2021-12-02 13:40 UTC, hors requested changes

2021-12-06 11:49 UTC, spron-in requested changes
Few more comments + my previous comments are not resolved.

2021-12-06 11:49 UTC, spron-in commented on source/options.rst
> +in a ``proxysql.conf`` configuration file using the following ``postgres-ha.yaml``
```suggestion
in a ``postgresql.conf`` configuration file using the following ``postgres-ha.yaml``
```

2021-12-06 11:49 UTC, spron-in commented on source/options.rst
> +For example, you can change ``max_connections`` option in a ``proxysql.conf``
```suggestion
For example, you can change ``max_connections`` option in a ``postgresql.conf``
```

2021-12-07 07:45 UTC, hors approved these changes

2021-12-07 07:49 UTC, merged