Merge 4.7.4
percona/percona-postgresql-operator pull request #186
Opened 2021-12-23 10:28 UTC by nonemax

2021-12-23 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/percona-postgresql-operator?pullRequest=186) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/percona/percona-postgresql-operator?pullRequest=186) before we can accept your contribution.<br/>**1** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nonemax<br/>:x: jmckulk<br/>:x: hstefan<br/>:x: jkatz<br/>:x: tjmoore4<br/>:x: ValClarkson<br/>:x: meobilivang<br/>:x: crunchyheath<br/>:x: sachincool<br/>:x: andrewlecuyer<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/percona-postgresql-operator?pullRequest=186) it.</sub>

2021-12-23 12:57 UTC, hors requested changes

2021-12-23 12:57 UTC, hors commented on build/pgo-deployer/Dockerfile
> +RUN mkdir -p /opt/cpm/bin
why do we need it (two the same lines)?

2021-12-23 15:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/d2067126d1b5e5aa2dc033daf7a5e2404e82cd50
image: `perconalab/percona-postgresql-operator:PR-186-d2067126-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-d2067126-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-d2067126-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-d2067126-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-d2067126-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-d2067126-pgo-deployer`

2021-12-23 21:26 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/bf4749c31a99e931ef47daeea4f384d0cb23cc71
image: `perconalab/percona-postgresql-operator:PR-186-bf4749c3-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-bf4749c3-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-bf4749c3-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-bf4749c3-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-bf4749c3-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-bf4749c3-pgo-deployer`

2021-12-24 12:18 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | failed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c71436c5f8bcee41ecbc6d51fbf59a502bfe7352
image: `perconalab/percona-postgresql-operator:PR-186-c71436c5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c71436c5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c71436c5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c71436c5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c71436c5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c71436c5-pgo-deployer`

2021-12-25 08:41 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | failed |
| scaling | failed |
| scheduled-backup | failed |
| recreate | failed |
| affinity | failed |
| monitoring | failed |
| self-healing | failed |
| operator-self-healing | failed |
| clone-cluster | failed |
| tls-check | failed |
| upgrade | failed |
| smart-update | failed |
| version-service | failed |
| users | failed |
| ns-mode | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c97c68cd35c1b89431093f77624f2e4d51ffae0e
image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-deployer`

2021-12-25 10:41 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c97c68cd35c1b89431093f77624f2e4d51ffae0e
image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-deployer`

2021-12-27 22:54 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c97c68cd35c1b89431093f77624f2e4d51ffae0e
image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-deployer`

2021-12-28 07:13 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | failed |
| scheduled-backup | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| monitoring | failed |
| self-healing | failed |
| operator-self-healing | failed |
| clone-cluster | failed |
| tls-check | failed |
| upgrade | failed |
| smart-update | failed |
| version-service | failed |
| users | failed |
| ns-mode | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c97c68cd35c1b89431093f77624f2e4d51ffae0e
image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-deployer`

2021-12-28 21:48 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | failed |
| scheduled-backup | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| monitoring | failed |
| self-healing | failed |
| operator-self-healing | failed |
| clone-cluster | failed |
| tls-check | failed |
| upgrade | failed |
| smart-update | failed |
| version-service | failed |
| users | failed |
| ns-mode | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c97c68cd35c1b89431093f77624f2e4d51ffae0e
image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-deployer`

2021-12-29 11:30 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| scheduled-backup | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c97c68cd35c1b89431093f77624f2e4d51ffae0e
image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-deployer`

2021-12-29 16:01 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/186/commits/c97c68cd35c1b89431093f77624f2e4d51ffae0e
image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-186-c97c68cd-pgo-deployer`

2022-01-03 12:27 UTC, hors approved these changes

2022-01-03 13:11 UTC, cap1984 approved these changes

2022-01-03 16:17 UTC, merged