K8SPG-169 Use percona native user secrets only
percona/percona-postgresql-operator pull request #198
Opened 2022-01-19 12:05 UTC by cap1984

2022-01-19 15:13 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| upgrade | passed |
| init-deploy | passed |
| smart-update | failed |
| scaling | passed |
| recreate | failed |
| version-service | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | failed |
| tls-check | passed |
| users | failed |
| ns-mode | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/198/commits/d5f5357d200de7f2950d857267bd3c366520836e
image: `perconalab/percona-postgresql-operator:PR-198-d5f5357d-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-198-d5f5357d-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-198-d5f5357d-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-198-d5f5357d-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-198-d5f5357d-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-198-d5f5357d-pgo-deployer`

2022-01-20 00:36 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| upgrade | passed |
| smart-update | passed |
| scaling | passed |
| version-service | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/198/commits/d043c351b9030e49f48c8ec5bf5d624df8e00798
image: `perconalab/percona-postgresql-operator:PR-198-d043c351-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-198-d043c351-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-198-d043c351-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-198-d043c351-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-198-d043c351-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-198-d043c351-pgo-deployer`

2022-01-20 12:51 UTC, hors requested changes

2022-01-20 12:51 UTC, hors commented on deploy/users-secret.yaml
> +type: Opaque
```suggestion
apiVersion: v1
kind: Secret
metadata:
  name: cluster1-pmm-secret
type: Opaque
stringData:
  password: admin
  username: admin
```

2022-01-20 12:51 UTC, hors commented on deploy/users-secret.yaml
> +type: Opaque
we need to fix pmm secret in CR

2022-01-20 15:52 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| upgrade | passed |
| init-deploy | passed |
| smart-update | passed |
| scaling | passed |
| version-service | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | failed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/198/commits/44b117a2770ba7b1a5116618c0ebe70f338f6d50
image: `perconalab/percona-postgresql-operator:PR-198-44b117a2-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-198-44b117a2-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-198-44b117a2-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-198-44b117a2-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-198-44b117a2-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-198-44b117a2-pgo-deployer`

2022-01-31 18:17 UTC, hors approved these changes

2022-01-31 18:18 UTC, merged