K8SPG-25 Add PMM
percona/percona-postgresql-operator pull request #30
Opened 2021-04-12 10:11 UTC by nonemax

2021-04-12 10:38 UTC, hors requested changes

2021-04-12 10:38 UTC, hors commented on internal/operator/cluster/clusterlogic.go
> +	if cl.Spec.PMM.Enabled {
please don't ignore settings from  supplementalGroups option

2021-04-12 11:36 UTC, qJkee approved these changes

2021-04-12 11:55 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| scaling | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/30/commits/b3d8807a69df547f2e696faff83e3aa516d460b6
image: `perconalab/percona-postgresql-operator:PR-30-b3d8807a-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-30-b3d8807a-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-30-b3d8807a-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-30-b3d8807a-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-30-b3d8807a-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-30-b3d8807a-pgo-deployer`

2021-04-12 12:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/30/commits/dc8c00748bbf22c4a230122fc5272166f1dc53ed
image: `perconalab/percona-postgresql-operator:PR-30-dc8c0074-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-30-dc8c0074-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-30-dc8c0074-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-30-dc8c0074-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-30-dc8c0074-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-30-dc8c0074-pgo-deployer`

2021-04-12 12:13 UTC, hors approved these changes

2021-04-12 13:54 UTC, cap1984 approved these changes

2021-04-12 16:15 UTC, hors commented on deploy/pmm-secret.yaml
> +  name: hippo-pmm-secret
@nonemax please fix it in main branch too

2021-04-13 06:57 UTC, nonemax commented on deploy/pmm-secret.yaml
> +  name: hippo-pmm-secret
done https://github.com/percona/percona-postgresql-operator/pull/30/commits/3eeb1afa10016e0ef4cd40e98d6e4f71684b7e12

2021-04-13 07:37 UTC, merged