K8SPG-265 A minor fix for monitoring test
percona/percona-postgresql-operator pull request #318
Opened 2022-12-16 16:08 UTC by cap1984

It turns out that pmm-server treats a node as entity with namespace as prefix inside a name

2022-12-16 16:14 UTC, egegunes approved these changes

2022-12-16 16:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/9cf42772/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/9cf42772/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/9cf42772/start-from-backup.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/9cf42772/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/318/commits/9cf42772906b87345cf7203d4d3aa671ed468f03
image: `perconalab/percona-postgresql-operator:PR-318-9cf42772`

2022-12-16 18:55 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/17a2fffc/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/17a2fffc/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/17a2fffc/start-from-backup.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/17a2fffc/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/318/commits/17a2fffc9bf34c80c43cfea9c643387f32713bb8
image: `perconalab/percona-postgresql-operator:PR-318-17a2fffc`

2022-12-19 07:50 UTC, tplavcic requested changes
Monitoring test has failed?

2022-12-19 11:23 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/903205e7/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/903205e7/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/903205e7/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-318/903205e7/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/318/commits/903205e78374544314fc637e9809b03894881b0a
image: `perconalab/percona-postgresql-operator:PR-318-903205e7`

2022-12-19 11:31 UTC, tplavcic approved these changes

2022-12-19 11:31 UTC, merged