K8SPG-316: Generate OLM bundles
percona/percona-postgresql-operator pull request #402
Opened 2023-04-07 11:17 UTC by egegunes

2023-04-07 11:53 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/3bb59a5ff/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/3bb59a5ff/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/3bb59a5ff/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/3bb59a5ff/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/402/commits/3bb59a5ff7677f00c8dc2af4198b2a4fb5b9d714
image: `perconalab/percona-postgresql-operator:PR-402-3bb59a5ff`

2023-04-18 11:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/0e9f78c41/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/0e9f78c41/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/0e9f78c41/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/0e9f78c41/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/402/commits/0e9f78c414141d15c01e62e4d8ae8e6ba473cbd8
image: `perconalab/percona-postgresql-operator:PR-402-0e9f78c41`

2023-04-18 16:24 UTC, hors requested changes

2023-04-18 16:24 UTC, hors commented on installers/olm/config/examples/postgrescluster.example.yaml
>  metadata:
Should we regenerate it to add finalizers?

2023-04-19 07:22 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/5487a96ff/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/5487a96ff/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/5487a96ff/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-402/5487a96ff/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/402/commits/5487a96ff32919da6c959b622c134ee110f281a1
image: `perconalab/percona-postgresql-operator:PR-402-5487a96ff`

2023-04-19 07:28 UTC, hors approved these changes

2023-04-19 07:28 UTC, merged