K8 spg 331
percona/percona-postgresql-operator pull request #410
Opened 2023-04-17 08:20 UTC by egegunes

**CHANGE DESCRIPTION**
---
**Problem:**
We want short name for our CRD.

**Solution:**
We added `pg` as short name.

**CHECKLIST**
---
**Jira**
- [x] Is the Jira ticket created and referenced properly?
- [x] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [x] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [x] Is an E2E test/test case added for the new feature/change?
- [x] Are unit tests added where appropriate?

**Config/Logging/Testability**
- [x] Are all needed new/changed options added to default YAML files?
- [x] Are the manifests (crd/bundle) regenerated if needed?
- [x] Did we add proper logging messages for operator actions?
- [x] Did we ensure compatibility with the previous version or cluster upgrade process?
- [x] Does the change support oldest and newest supported PG version?
- [x] Does the change support oldest and newest supported Kubernetes version?

2023-04-17 09:02 UTC, inelpandzic requested changes
What about other resources, `pg-backup` and `pg-resotre`?

2023-04-17 11:08 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-410/be6253050/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-410/be6253050/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-410/be6253050/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-410/be6253050/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/410/commits/be6253050ba0041c4ae4b2764d2f0d0b70d5ad06
image: `perconalab/percona-postgresql-operator:PR-410-be6253050`

2023-04-17 11:52 UTC, inelpandzic approved these changes

2023-04-18 08:15 UTC, hors approved these changes

2023-04-18 09:17 UTC, merged