K8SPG-303 Scheduled backup e2e test
percona/percona-postgresql-operator pull request #417
Opened 2023-04-25 10:25 UTC by cap1984

Making sure the backup schedule and multiple repos do work

**CHANGE DESCRIPTION**
---
**Problem:**
*No backup schedule process verification.*

**Cause:**
*Early v5 adoption.*

**Solution:**
*Adding the respective e2e test*

**CHECKLIST**
---
**Jira**
- [x] Is the Jira ticket created and referenced properly?
- [x] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [X] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [ ] Is an E2E test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

**Config/Logging/Testability**
- [ ] Are all needed new/changed options added to default YAML files?
- [ ] Are the manifests (crd/bundle) regenerated if needed?
- [ ] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [ ] Does the change support oldest and newest supported PG version?
- [ ] Does the change support oldest and newest supported Kubernetes version?

2023-04-25 12:45 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/bfe18bec1/init-deploy.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/bfe18bec1/demand-backup.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/bfe18bec1/scheduled-backup.log) |
| start-from-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/bfe18bec1/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/bfe18bec1/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/bfe18bec1/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/417/commits/bfe18bec1d61809eb58355c748843ce57176c850
image: `perconalab/percona-postgresql-operator:PR-417-bfe18bec1`

2023-04-25 18:33 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/17678b9a6/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/17678b9a6/demand-backup.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/17678b9a6/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/17678b9a6/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/17678b9a6/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/17678b9a6/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/417/commits/17678b9a67a6815ed88d9393764d6c956d7a7de8
image: `perconalab/percona-postgresql-operator:PR-417-17678b9a6`

2023-04-26 07:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/5647954a4/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/5647954a4/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/5647954a4/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/5647954a4/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/5647954a4/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/5647954a4/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/417/commits/5647954a49e6087225161bb340a344f072df57a5
image: `perconalab/percona-postgresql-operator:PR-417-5647954a4`

2023-04-26 08:28 UTC, tplavcic requested changes

2023-04-26 08:28 UTC, tplavcic commented on e2e-tests/functions
> +			yq eval '.spec.backups.pgbackrest.configuration = [{"secret":{"name":"'${test_name}'-pgbackrest-secrets"}}]' "${TEMP_DIR}/cr.yaml" \
`yq` supports writing multiple commands in a single command, something like:
```
    yq eval '
        .metadata.name = "chaos-cluster-pod-kill" |
        del(.spec.selector.pods.test-namespace) |
        .spec.selector.pods.'$namespace'[0] = "'$pod'"' $conf_dir/chaos-pod-kill.yml \
        | kubectl apply -f -
```
might be a bit shorter and faster then piping

2023-04-26 08:28 UTC, tplavcic commented on e2e-tests/tests/scheduled-backup/03-assert.yaml
> +  data: ' 100500'
Why empty space before number?

2023-04-26 08:32 UTC, cap1984 commented on e2e-tests/tests/scheduled-backup/03-assert.yaml
> +  data: ' 100500'
yeah, it's a part of psql output

2023-04-26 10:51 UTC, nmarukovich submitted a review, later dismissed

2023-04-26 13:25 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/e5139ed04/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/e5139ed04/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/e5139ed04/scheduled-backup.log) |
| start-from-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/e5139ed04/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/e5139ed04/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/e5139ed04/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/417/commits/e5139ed04de63b4c3db68f95abfb82f6f38d3aee
image: `perconalab/percona-postgresql-operator:PR-417-e5139ed04`

2023-04-26 15:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/7f2908183/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/7f2908183/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/7f2908183/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/7f2908183/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/7f2908183/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-417/7f2908183/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/417/commits/7f290818341c294fc6333af779be52cb446b6989
image: `perconalab/percona-postgresql-operator:PR-417-7f2908183`

2023-04-27 06:30 UTC, tplavcic approved these changes

2023-04-27 07:02 UTC, nmarukovich approved these changes

2023-04-27 07:03 UTC, merged