K8 spg 251 update readme
percona/percona-postgresql-operator pull request #431
Opened 2023-05-01 23:05 UTC by fiowro

* add Kubernetes Operator logo to README
* change README to have more consist features list

2023-05-01 23:05 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-postgresql-operator?pullRequest=431) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-postgresql-operator?pullRequest=431) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-postgresql-operator?pullRequest=431) it.</sub>

2023-05-02 00:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/2546385bf/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/2546385bf/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/2546385bf/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/2546385bf/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/2546385bf/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/2546385bf/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/431/commits/2546385bf50d1cae928edc5313b8a7c43e9872ea
image: `perconalab/percona-postgresql-operator:PR-431-2546385bf`

2023-05-02 06:16 UTC, inelpandzic requested changes

2023-05-02 06:16 UTC, inelpandzic commented on README.md
> +- Integrated monitoring with [Percona Monitoring and Management](https://www.percona.com/software/database-tools/percona-monitoring-and-management)
@fiowro I can see this list has a center alignment, is it on purpose?

2023-05-04 17:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/c5fde634e/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/c5fde634e/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/c5fde634e/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/c5fde634e/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/c5fde634e/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-431/c5fde634e/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/431/commits/c5fde634e05d81c2175de9c972a2e9e1dd622605
image: `perconalab/percona-postgresql-operator:PR-431-c5fde634e`

2023-05-08 14:03 UTC, hors approved these changes

2023-05-09 10:15 UTC, merged