K8SPG-359 Added support for custom user secret name
percona/percona-postgresql-operator pull request #442
Opened 2023-05-11 13:04 UTC by vishalanarase

**CHANGE DESCRIPTION**
---
**Problem:**
*There wasn't support for a custom user secret name.  There was fix pattern to generate the name*

**Cause:**
*When the user gives cr name of more than 63 characters secret isn't created so can't access the creds*

**Solution:**
*This PR adds support for custom user secret name*

**CHECKLIST**
---
**Jira**
- [x] Is the Jira ticket created and referenced properly?
- [ ] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [ ] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [ ] Is an E2E test/test case added for the new feature/change?
- [x] Are unit tests added where appropriate?

**Config/Logging/Testability**
- [ ] Are all needed new/changed options added to default YAML files?
- [ ] Are the manifests (crd/bundle) regenerated if needed?
- [ ] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [ ] Does the change support oldest and newest supported PG version?
- [ ] Does the change support oldest and newest supported Kubernetes version?

2023-05-11 13:04 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-postgresql-operator?pullRequest=442) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-postgresql-operator?pullRequest=442) before we can accept your contribution.<br/><hr/>**Vishal Anarse** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-postgresql-operator?pullRequest=442) it.</sub>

2023-05-11 14:16 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/a91303e53/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/a91303e53/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/a91303e53/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/a91303e53/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/a91303e53/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/a91303e53/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/442/commits/a91303e536bdc382abb2def5a8868bee46480e8a
image: `perconalab/percona-postgresql-operator:PR-442-a91303e53`

2023-05-11 17:56 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e1615001a/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e1615001a/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e1615001a/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e1615001a/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e1615001a/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e1615001a/telemetry-transfer.log) |
| We run 6 out of 6|

commit: https://github.com/percona/percona-postgresql-operator/pull/442/commits/e1615001a2ccd6cb8d13adf79857f9e12da8674e
image: `perconalab/percona-postgresql-operator:PR-442-e1615001a`

2023-05-12 07:16 UTC, hors requested changes

2023-05-12 07:16 UTC, hors commented on deploy/bundle.yaml
> +        image: perconalab/percona-postgresql-operator:k8spg-359-improvement-user-defined-secret-name
```suggestion
        image: perconalab/percona-postgresql-operator:main
```

2023-05-12 07:16 UTC, hors commented on deploy/operator.yaml
> +        image: perconalab/percona-postgresql-operator:k8spg-359-improvement-user-defined-secret-name
```suggestion
        image: perconalab/percona-postgresql-operator:main
```

2023-05-12 07:16 UTC, hors commented on config/manager/kustomization.yaml
> +  newTag: k8spg-359-improvement-user-defined-secret-name
```suggestion
  newTag: main
```

2023-05-12 07:16 UTC, hors commented on config/bundle/kustomization.yaml
> +  newTag: k8spg-359-improvement-user-defined-secret-name
```suggestion
  newTag: main
```

2023-05-12 07:24 UTC, hors requested changes

2023-05-12 07:24 UTC, hors commented on testing/kuttl/e2e/password-change/12--custom-user-secret-name.yaml
Please move test to /e2e-tests/tests/

2023-05-12 10:22 UTC, egegunes commented
@vishalanarase you need to put this field to our custom resource: https://github.com/percona/percona-postgresql-operator/blob/main/pkg/apis/pg.percona.com/v2beta1/perconapgcluster_types.go#L38

and then you need to map this field to crunchy CR in: https://github.com/percona/percona-postgresql-operator/blob/main/percona/controller/pgcluster/controller.go#L144-L213

otherwise you can't use this field through our custom resources

2023-05-15 06:34 UTC, vishalanarase commented
> @vishalanarase you need to put this field to our custom resource: https://github.com/percona/percona-postgresql-operator/blob/main/pkg/apis/pg.percona.com/v2beta1/perconapgcluster_types.go#L38
> 
> and then you need to map this field to crunchy CR in: https://github.com/percona/percona-postgresql-operator/blob/main/percona/controller/pgcluster/controller.go#L144-L213
> 
> otherwise you can't use this field through our custom resources

I can't see the `PostgresUserSpec` struct in your types. I see it only in the https://github.com/percona/percona-postgresql-operator/blob/main/pkg/apis/postgres-operator.crunchydata.com/v1beta1/postgres_types.go#L41

2023-05-15 06:38 UTC, vishalanarase commented on config/bundle/kustomization.yaml
> +  newTag: k8spg-359-improvement-user-defined-secret-name
Done

2023-05-15 06:38 UTC, vishalanarase commented on config/manager/kustomization.yaml
> +  newTag: k8spg-359-improvement-user-defined-secret-name
Done

2023-05-15 06:38 UTC, vishalanarase commented on deploy/bundle.yaml
> +        image: perconalab/percona-postgresql-operator:k8spg-359-improvement-user-defined-secret-name
Done

2023-05-15 06:38 UTC, vishalanarase commented on deploy/operator.yaml
> +        image: perconalab/percona-postgresql-operator:k8spg-359-improvement-user-defined-secret-name
Done

2023-05-15 06:49 UTC, vishalanarase commented on testing/kuttl/e2e/password-change/12--custom-user-secret-name.yaml
Done

2023-05-15 07:50 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/8270302b9/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/8270302b9/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/8270302b9/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/8270302b9/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/8270302b9/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/8270302b9/telemetry-transfer.log) |
| We run 6 out of 7|

commit: https://github.com/percona/percona-postgresql-operator/pull/442/commits/8270302b99267052c0c2582153a88c7654d1eb6d
image: `perconalab/percona-postgresql-operator:PR-442-8270302b9`

2023-05-16 09:00 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e4865f4f9/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e4865f4f9/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e4865f4f9/scheduled-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e4865f4f9/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e4865f4f9/monitoring.log) |
| telemetry-transfer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-442/e4865f4f9/telemetry-transfer.log) |
| We run 6 out of 7|

commit: https://github.com/percona/percona-postgresql-operator/pull/442/commits/e4865f4f93fbea5c729862ed0ca3630911e84076
image: `perconalab/percona-postgresql-operator:PR-442-e4865f4f9`

2023-05-16 15:28 UTC, hors approved these changes

2023-05-17 06:04 UTC, vishalanarase commented
Need one more approval @egegunes can please review and approve?

2023-05-17 07:23 UTC, egegunes approved these changes

2023-05-17 11:28 UTC, merged

2023-05-17 17:58 UTC, hors commented
@vishalanarase thank you for conrebution