K8SPG-362: Serve v1 in v2 CRD
percona/percona-postgresql-operator pull request #446
Opened 2023-05-17 13:43 UTC by egegunes

**CHANGE DESCRIPTION**
---
**Problem:**
*Short explanation of the problem.*

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?
- [ ] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [ ] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [ ] Is an E2E test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

**Config/Logging/Testability**
- [ ] Are all needed new/changed options added to default YAML files?
- [ ] Are the manifests (crd/bundle) regenerated if needed?
- [ ] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [ ] Does the change support oldest and newest supported PG version?
- [ ] Does the change support oldest and newest supported Kubernetes version?

2023-05-19 07:17 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-446/8f0479f2b/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-446/8f0479f2b/demand-backup.log) |
| start-from-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-446/8f0479f2b/start-from-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-446/8f0479f2b/monitoring.log) |
| We run 4 out of 4|

commit: https://github.com/percona/percona-postgresql-operator/pull/446/commits/8f0479f2b57f9c1b3910514ae8df92540dec8ff2
image: `perconalab/percona-postgresql-operator:PR-446-8f0479f2b`

2023-05-19 17:05 UTC, hors approved these changes

2023-05-19 17:06 UTC, hors requested changes
@egegunes, what about CW? It does not work now but we should not forgot to add these changes to these files

2023-05-22 09:47 UTC, hors approved these changes

2023-05-22 09:48 UTC, hors commented
> @egegunes, what about CW? It does not work now but we should not forgot to add these changes to these files

will be fixed under  https://jira.percona.com/browse/K8SPG-355

2023-05-22 09:48 UTC, merged