updating versions
percona/percona-postgresql-operator pull request #583
Opened 2023-11-22 14:12 UTC by ptankov

2023-11-22 16:14 UTC, tplavcic requested changes

2023-11-22 16:14 UTC, tplavcic commented on deploy/cr.yaml
> +    image: perconalab/percona-postgresql-operator:main-ppg15-postgres-ha
We need to change these to the ones which will be for the release, like: `percona/percona-postgresql-operator:1.5.0-ppg14-postgres-ha`.
You can have a look at the list of official images in the doc page: https://docs.percona.com/percona-operator-for-postgresql/1.0/images.html
Same for all of the below images in cr.yaml
Also we need to change `percona/pmm-client:2.36.0` to the current latest version.

2023-11-22 16:14 UTC, tplavcic commented on installers/ansible/values.yaml
> +ccp_image_tag: "main-ppg15-postgres-ha"
ppg14 is staying here, since we will not support PG 15 in this release, but we need to see what was here on the previous release

2023-11-22 19:39 UTC, hors requested changes

2023-11-22 19:39 UTC, hors commented on deploy/cr.yaml
> +    image: percona/percona-postgresql-operator:1.5.0-ppg15-postgres-ha
we do not support pg 15 in v1 operator

2023-11-22 21:35 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/scheduled-backup.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/upgrade.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/version-service.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/init-deploy.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-583/13b5432c1/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/583/commits/13b5432c18f4e15919b5e3f0897481e628cfc597
image: `perconalab/percona-postgresql-operator:PR-583-13b5432c1-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-583-13b5432c1-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-583-13b5432c1-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-583-13b5432c1-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-583-13b5432c1-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-583-13b5432c1-pgo-deployer`

2023-11-23 08:26 UTC, ptankov commented on deploy/cr.yaml
> +    image: percona/percona-postgresql-operator:1.5.0-ppg15-postgres-ha
sorry, IDK how this one slipped through

2023-11-23 08:30 UTC, tplavcic approved these changes

2023-11-23 08:36 UTC, merged