K8SPG-64 Test compliance with openshift
percona/percona-postgresql-operator pull request #66
Opened 2021-05-13 10:08 UTC by cap1984

2021-05-13 11:57 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/743797635809b13f43599792abe1fd1167459467
image: `perconalab/percona-postgresql-operator:PR-66-74379763-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-74379763-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-74379763-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-74379763-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-74379763-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-74379763-pgo-deployer`

2021-05-13 16:03 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/b9cdf41495477ae1d467b9e9ed0a29fcc07ae54e
image: `perconalab/percona-postgresql-operator:PR-66-b9cdf414-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-b9cdf414-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-b9cdf414-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-b9cdf414-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-b9cdf414-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-b9cdf414-pgo-deployer`

2021-05-13 21:23 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/7f375054f5e0662427be6eb3a2577252ac1f8493
image: `perconalab/percona-postgresql-operator:PR-66-7f375054-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-7f375054-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-7f375054-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-7f375054-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-7f375054-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-7f375054-pgo-deployer`

2021-05-14 08:23 UTC, hors requested changes

2021-05-14 08:23 UTC, hors commented on e2e-tests/functions
> +	if [ ! -z "$OPENSHIFT" ]; then
```suggestion
	if [ -n "$OPENSHIFT" ]; then
```

2021-05-14 08:23 UTC, hors commented on e2e-tests/functions
> +	if [ ! -z "$OPENSHIFT" -a -f ${expected_result//.yml/-oc.yml} ]; then
```suggestion
	if [ -n "$OPENSHIFT" -a -f ${expected_result//.yml/-oc.yml} ]; then
```

2021-05-18 13:00 UTC, cap1984 commented on e2e-tests/functions
> +	if [ ! -z "$OPENSHIFT" ]; then
done

2021-05-18 13:00 UTC, cap1984 commented on e2e-tests/functions
> +	if [ ! -z "$OPENSHIFT" -a -f ${expected_result//.yml/-oc.yml} ]; then
done

2021-05-18 14:47 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/0a387f7b928b6ed470fdd71ea42a29c18b69ff02
image: `perconalab/percona-postgresql-operator:PR-66-0a387f7b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-0a387f7b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-0a387f7b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-0a387f7b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-0a387f7b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-0a387f7b-pgo-deployer`

2021-05-22 22:08 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/81dcb18649730390a1755afaf1598240bb30077a
image: `perconalab/percona-postgresql-operator:PR-66-81dcb186-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-81dcb186-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-81dcb186-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-81dcb186-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-81dcb186-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-81dcb186-pgo-deployer`

2021-05-24 19:52 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/825f7c42c67b7269c8e486af41cb9d84f7e109fe
image: `perconalab/percona-postgresql-operator:PR-66-825f7c42-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-825f7c42-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-825f7c42-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-825f7c42-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-825f7c42-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-825f7c42-pgo-deployer`

2021-05-25 10:02 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/5331af3b5f33f8de7402ebd404b7daf4afd8f9ed
image: `perconalab/percona-postgresql-operator:PR-66-5331af3b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-5331af3b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-5331af3b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-5331af3b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-5331af3b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-5331af3b-pgo-deployer`

2021-06-08 08:52 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/eaa8e570127afd12bd57179d2aaa3cbef206d809
image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-deployer`

2021-06-10 12:46 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/66/commits/eaa8e570127afd12bd57179d2aaa3cbef206d809
image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-66-eaa8e570-pgo-deployer`

2021-06-15 14:43 UTC, closed without merging