K8SPG-33 gke install
percona/percona-postgresql-operator pull request #68
Opened 2021-05-27 23:19 UTC by fiowro

2021-06-11 12:41 UTC, spron-in requested changes

2021-06-11 12:41 UTC, spron-in commented on source/gke.rst
> +   operator and replica set pod have reached their Running status:
```suggestion
   Creation process will take some time. The process is over when operator and PostgreSQL pods have reached their Running status:
```

2021-06-11 12:41 UTC, spron-in commented on source/gke.rst
> +#. You can also deploy PosgreSQL replica at any time as follows:
```suggestion
#. You can also deploy PostgreSQL replica at any time as follows:
```

2021-07-27 08:45 UTC, spron-in approved these changes

2021-07-27 16:38 UTC, hors requested changes

2021-07-27 16:38 UTC, hors commented on source/gke.rst
> +
in 0.2.0 we will configure  PostgreSQL replicas via `deploy/cr.yaml`

2021-07-30 16:52 UTC, hors approved these changes

2021-07-30 16:53 UTC, merged