K8SPG-67 document helm chart
percona/percona-postgresql-operator pull request #94
Opened 2021-08-05 23:22 UTC by fiowro

2021-08-11 07:09 UTC, cap1984 commented on source/helm.rst
> +      $ helm install my-operator percona/postgres-operator --version {{{release}}}
pg-operator

2021-08-11 11:40 UTC, cap1984 approved these changes

2021-08-11 19:54 UTC, spron-in requested changes
just a minor fix. looks good overall.

2021-08-11 19:54 UTC, spron-in commented on source/helm.rst
> +and 20 Gi storage:
```suggestion
and 20 Gi storage for a Primary PostgreSQL node:
```

2021-08-12 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/percona-postgresql-operator?pullRequest=94) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/percona/percona-postgresql-operator?pullRequest=94) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: fiowro<br/>:x: spron-in<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/percona-postgresql-operator?pullRequest=94) it.</sub>

2021-08-12 10:52 UTC, spron-in approved these changes

2021-08-12 10:54 UTC, merged