K8SPG-59 add gcs support to backup docs
percona/percona-postgresql-operator pull request #98
Opened 2021-08-06 15:09 UTC by fiowro

2021-08-11 07:13 UTC, cap1984 approved these changes

2021-08-11 19:48 UTC, spron-in requested changes
GCS looks good to me.

Some parts of the doc must be reworked.

1. We introduce GCS, but at the top we say "The Operator usually stores PostgreSQL backups on `Amazon S3 or S3-compatible"
2. pgBackRest repository must include gcs:
```
* ``local``: Uses the storage that is provided by the Kubernetes cluster’s
  Storage Class that you select,
* ``s3``: Use Amazon S3 or an object storage system that uses the S3 protocol,
* ``local,s3``: Use both the storage that is provided by the Kubernetes
  cluster’s Storage Class that you select AND Amazon S3 (or equivalent object
  storage system that uses the S3 protocol).
```

Where is GCS here? ^^^

3. Where these flags should be set:
```
* Full (``full``): A full backup of all the contents of the PostgreSQL cluster,
* Differential (``diff``): A backup of only the files that have changed since
  the last full backup,
* Incremental (``incr``): A backup of only the files that have changed since the
  last full or differential backup. Incremental backup is the default choice.

The Operator also supports setting pgBackRest retention policies for backups.
Backup retention can be controlled by the following pgBackRest options:
* ``--repo1-retention-full`` the number of full backups to retain,
* ``--repo1-retention-diff`` the number of differential backups to retain,
* ``--repo1-retention-archive`` how many sets of write-ahead log archives to
  retain alongside the full and differential backups that are retained.
```
?

We should clarify that it is in backup.yaml.

4. There are no such options in CR anymore:
```
* ``BackrestS3Bucket`` specifies the AWS S3 bucket that should be utilized,
  for example ``my-postgresql-backups-example``,
* ``BackrestS3Endpoint`` specifies the S3 endpoint that should be utilized,
  for example ``s3.amazonaws.com``,
* ``BackrestS3Region`` specifies the AWS S3 region that should be utilized,
  for example ``us-east-1``,
* ``BackrestS3URIStyle`` specifies whether ``host`` or ``path`` style URIs
  should be utilized,
* ``BackrestS3VerifyTLS`` should be set to ``true`` to enable TLS verification
  or set to ``false`` to disable it.
```

2021-08-12 10:25 UTC, cap1984 commented
@fiowro please update backup section according to https://github.com/percona/percona-postgresql-operator/blob/a8d9d9ecadf1d96f32368f33ae246a6015c7d667/deploy/cr.yaml#L92

2021-08-12 12:53 UTC, spron-in approved these changes

2021-08-12 13:23 UTC, cap1984 approved these changes

2021-08-12 13:26 UTC, merged