K8SPG-91 Configurable SecurityContext
percona/percona-postgresql-operator pull request #99
Opened 2021-08-09 10:56 UTC by nonemax

2021-08-09 11:34 UTC, hors requested changes

2021-08-09 11:34 UTC, hors commented on percona/controllers/pgc/pgc.go
> +	defaultSecurityContext = `{"fsGroup": 1001,"supplementalGroups": [1001, 1002, 1003]}`
pgo uses fsGroup 26 by default and all containers use 26

2021-08-09 11:38 UTC, qJkee commented on percona/controllers/deployment/deployment.go
> +func UpdateSpecTemplaeSpecSecurityContext(cl *crv1.PerconaPGCluster, deployment *appsv1.Deployment) {
```suggestion
func UpdateSpecTemplateSpecSecurityContext(cl *crv1.PerconaPGCluster, deployment *appsv1.Deployment) {
```

2021-08-09 13:03 UTC, qJkee approved these changes

2021-08-09 23:14 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| clone-cluster | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/99/commits/5e494e13fb84ab180a10bf4d84a04ad7cc2bab6b
image: `perconalab/percona-postgresql-operator:PR-99-5e494e13-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-99-5e494e13-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-99-5e494e13-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-99-5e494e13-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-99-5e494e13-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-99-5e494e13-pgo-deployer`

2021-08-10 10:20 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| clone-cluster | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/99/commits/7fccabf3a17a025d11d08488dd7cf7abb54dfc31
image: `perconalab/percona-postgresql-operator:PR-99-7fccabf3-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-99-7fccabf3-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-99-7fccabf3-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-99-7fccabf3-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-99-7fccabf3-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-99-7fccabf3-pgo-deployer`

2021-08-10 13:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| clone-cluster | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/99/commits/991f1ce493b40c1eaedb2e7b40572c72720d11e7
image: `perconalab/percona-postgresql-operator:PR-99-991f1ce4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-99-991f1ce4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-99-991f1ce4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-99-991f1ce4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-99-991f1ce4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-99-991f1ce4-pgo-deployer`

2021-08-10 13:24 UTC, hors approved these changes

2021-08-10 13:26 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| clone-cluster | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/99/commits/bec2d96756fded4659e9ae45be461ee3bbe2b630
image: `perconalab/percona-postgresql-operator:PR-99-bec2d967-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-99-bec2d967-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-99-bec2d967-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-99-bec2d967-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-99-bec2d967-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-99-bec2d967-pgo-deployer`

2021-08-10 13:30 UTC, cap1984 approved these changes

2021-08-10 13:31 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| clone-cluster | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/99/commits/fce487f6d0dd4b0587ac347a8e2799eadc4b0c84
image: `perconalab/percona-postgresql-operator:PR-99-fce487f6-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-99-fce487f6-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-99-fce487f6-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-99-fce487f6-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-99-fce487f6-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-99-fce487f6-pgo-deployer`

2021-08-10 13:32 UTC, merged